# -*- coding: utf-8 -*-
"""Samira_Donkoh_Lab4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mD4_-tu_y7Oq1ek5Lb9AdTPbK-nJ6QbG
"""

##Student Name: Samira Ewura-Esi Donkoh
##Student ID: 20962028

# API-key setup — DO NOT hard-code your key in this cell.

import os
from google.colab import userdata
from openai import OpenAI
# --- Local (with a .env file) ---
# from dotenv import load_dotenv
# load_dotenv()
# API_KEY = os.environ["GROQ_API_KEY"]

# --- Google Colab (Secrets panel) ---
# from google.colab import userdata
# API_KEY = userdata.get("GROQ_API_KEY")

# TODO: set API_KEY using ONE of the methods above.
API_KEY=userdata.get("GROQ_API_KEY")
# OpenAI-compatible client (works for Groq and OpenAI; Gemini users see their docs):


client = OpenAI(
    api_key=API_KEY,
    base_url="https://api.groq.com/openai/v1",   # remove this line if using OpenAI itself
)
MODEL = "llama-3.3-70b-versatile"                # or your provider's model name

print("Client ready.")

# TODO: Write a helper function you will reuse for the WHOLE lab:

def ask_llm(user_prompt, system_prompt="You are a helpful assistant.",
             temperature=0.7, max_tokens=500):
     response = client.chat.completions.create(
         model=MODEL,
         messages=[
             {"role": "system", "content": system_prompt},
             {"role": "user",   "content": user_prompt},
         ],
         temperature=temperature,
         max_tokens=max_tokens,
     )
     return response

# TODO: Call it once with a simple question and print the answer.
# TODO: Print response.usage as well — how many tokens did your call consume?
response=ask_llm("What is the capital of Ghana")
print(response.choices[0].message.content)
print(response.usage)

# TODO: Ask the SAME question 5 times at temperature=0.0 and 5 times at temperature=1.2.
#   A good test question: "Suggest a name for a savings product for market traders in Accra."
question="Suggest a name for a savings product for market traders in Accra."
print("AT TEMPERATURE 0.0")
for i in range(5):
  response=ask_llm(question,temperature=0.0)
  print(f"{i+1}.{response.choices[0].message.content}")

  # TODO: Print all 10 answers, grouped by temperature.
print("AT TEMPERATURE 1.2")
for i in range(5):
  response=ask_llm(question,temperature=1.2)
  print(f"{i+1}.{response.choices[0].message.content}")

LETTERS = {
"L001": """Dear Sir/Madam,
My name is Akosua Mensah and I have been selling provisions at Makola Market for 12 years.
I am applying for a loan of GHS 8,000 to buy a deep freezer and expand into frozen foods.
My current stall makes about GHS 900 profit each month. I have saved GHS 2,500 with your
susu scheme over the past two years and I have never missed a contribution. I can repay
GHS 450 monthly over 20 months. My sister, a teacher, will stand as my guarantor.
Thank you for considering my application.""",

"L002": """Hello,
I am Kwame Boateng, a commercial driver in Kumasi. I need GHS 25,000 urgently to repair my
trotro engine and settle some personal debts. Business has been slow but it will surely
pick up after the festive season. I can pay back whenever the money comes. I do not have
collateral at the moment but God willing everything will be fine. Please help me quickly.""",

"L003": """Dear Loan Committee,
I am Efua Darko, owner of Darko Fashions, a registered dressmaking business in Takoradi
(registration no. BN-2019-4482). I employ three apprentices. I request GHS 15,000 to
purchase two industrial sewing machines and fabric stock ahead of the Christmas season.
Last year my December revenue alone was GHS 22,000; monthly profit averages GHS 2,800.
I hold a fixed deposit of GHS 5,000 with GCB which I can pledge. Proposed repayment:
GHS 1,100 monthly for 15 months. Attached are my sales records for the past 18 months.""",

"L004": """Good day,
My name is Yaw Owusu. I want a loan for my poultry farm at Nsawam. The amount is GHS 12,000
for feed and 500 new layers. I started the farm last year. Sometimes I make good money,
around GHS 1,500 in a good month, but bird flu affected us in March and I lost many birds.
I am rebuilding now. I can repay in 18 months. My uncle has agreed to guarantee the loan
with his taxi.""",

"L005": """Dear Manager,
I am writing on behalf of the Adenta Women's Weaving Cooperative (14 members). We seek
GHS 30,000 to buy a bulk order of yarn directly from the factory, cutting out middlemen and
raising our margins from 15% to about 35%. The cooperative has operated for 6 years and
holds GHS 9,000 in our group account. We propose repayment of GHS 2,000 monthly over
16 months, backed by our group savings and joint liability agreement.""",

"L006": """Hi,
This is Kofi. I saw your advert. I want GHS 50,000 to start a car washing business, a
provision shop, and also import phones from Dubai. I am 22 and full of energy. I have not
started any of these yet but my friends say I am very business minded. I will pay back in
one year when the businesses are booming. No collateral but I am trustworthy.""",
}

# Gold-standard labels for three letters (for Section 4 evaluation):
GOLD = {
  "L001": {"applicant_name": "Akosua Mensah", "amount_ghs": 8000,  "purpose": "buy deep freezer / expand into frozen foods",
           "monthly_profit_ghs": 900,  "has_collateral_or_guarantor": True,  "repayment_months": 20},
  "L003": {"applicant_name": "Efua Darko",    "amount_ghs": 15000, "purpose": "industrial sewing machines and fabric stock",
           "monthly_profit_ghs": 2800, "has_collateral_or_guarantor": True,  "repayment_months": 15},
  "L006": {"applicant_name": "Kofi",          "amount_ghs": 50000, "purpose": "car wash, provision shop, phone imports",
           "monthly_profit_ghs": None, "has_collateral_or_guarantor": False, "repayment_months": 12},
}

print(f"{len(LETTERS)} letters loaded.")

# TODO: Write SUMMARY_PROMPT_V1 — your first, naive attempt (e.g. just "Summarize this:").
#   Run it on L002 and L006. Read the output critically.
SUMMARY_PROMPT_V1="Summarize this:"
v1_l002=ask_llm(f"{SUMMARY_PROMPT_V1}\n\n{LETTERS['L002']}")
v1_l006=ask_llm(f"{SUMMARY_PROMPT_V1}\n\n{LETTERS['L006']}")
print("V1-L002")
print(v1_l002.choices[0].message.content)
print("V1-L006")
print(v1_l006.choices[0].message.content)
# TODO: Now write SUMMARY_PROMPT_V2 as a proper template with:
#   - a system prompt giving the LLM a ROLE (e.g. "You are an assistant to a microfinance
#     loan officer...") and constraints (factual, neutral, no invented details, 3-4 sentences)
#   - a user prompt template like: f"Summarize this loan application:\n\n{letter_text}"
#   Run V2 on the same two letters at temperature=0.
SUMMARY_PROMPT_V2="""
You are an assistant to a microfinance loan officer. Summarize loan applications
factually and neutrally. Do not invent or assume or add details that are not present
in the application. Summarize it to 3-4 sentences."""
# TODO: Compare V1 vs V2 outputs side by side. Keep both prompt versions in this notebook.
def summary_prompt_v2(letter_text):
  return f"Summarize this loan application:\n\n{letter_text}"
v2_l002=ask_llm(summary_prompt_v2(LETTERS["L002"]), system_prompt=SUMMARY_PROMPT_V2,
                temperature=0)
v2_l006=ask_llm(summary_prompt_v2(LETTERS["L006"]), system_prompt=SUMMARY_PROMPT_V2,
                temperature=0)
print("\n" + "=" * 50)
print("V2-L002")
print("=" * 50)
print(v2_l002.choices[0].message.content)

print("\n" + "=" * 50)
print("V2-L006")
print("=" * 50)
print(v2_l006.choices[0].message.content)

print("\n" + "=" * 60)
print("Compared")
print("=" *60)

print("\nL002-V1")
print(v1_l002.choices[0].message.content)

print("\nL002-V2")
print(v2_l002.choices[0].message.content)

print("\nL006-V1")
print(v1_l006.choices[0].message.content)

print("\nL006-V2")
print(v2_l006.choices[0].message.content)

import json
import pandas as pd
# TODO: Write EXTRACT_PROMPT — a template that instructs the model to return ONLY a JSON
#   object with EXACTLY these keys:
#     applicant_name (string), amount_ghs (number), purpose (string),
#     monthly_profit_ghs (number or null), has_collateral_or_guarantor (boolean),
#     repayment_months (number or null)
#   Techniques to use:
#     - explicit schema in the prompt
#     - ONE worked example (few-shot) using a letter you write yourself (not from LETTERS!)
#     - "If a field is not stated in the letter, use null. Do not guess."
#     - temperature=0
EXTRACT_PROMPT=''' You are a model acting as an assistant to help a microfinance
loan officer get structured information from various loan applications. You are to return only
a JSON object with the following keys:
{applicant_name(string), amount_ghs (number), purpose (string),
monthly_profit_ghs (number or null), has_collateral_or_guarantor (boolean),
repayment_months (number or null)}

- If a field is not stated in the letter, use null. Do not guess.
example- "Ama Acheampong wants GHS 50000 for a building project shes working on. Her
monthly profit from her personal business is GHS 3000 and her uncle is her guarantor. She will
repay the loan in 2 years."

JSON: {"applicant_name":"Ama Acheampong","amount_ghs": 50000, "purpose": "Building project",
"monthly_profit_ghs":3000, "has_collateral_or_guarantor":true, "repayment_months":24}

Return ONLY JSON
'''

# TODO: Write extract_fields(letter_text) that calls the LLM, strips any ```json fences,
#   json.loads() the result, and returns a dict. Handle parse failures gracefully
#   (return None and print a warning).
def extract_fields(letter_text, temperature=0):
  try:
    response=ask_llm(f"{EXTRACT_PROMPT}\n\n{letter_text}",temperature=0)
    result=response.choices[0].message.content.strip()
    if result.startswith("```json"):
      result=result[7:]
    if result.endswith("```"):
      result=result[:-3]
    result=result.strip()
    return json.loads(result)
  except Exception as e:
    print(f"Warning:Could not parse response {e}")
    return None
# TODO: Run it on ALL SIX letters; collect results into a pandas DataFrame (one row per
#   letter) and display it.
letters=[LETTERS["L001"],LETTERS["L002"],LETTERS["L003"],
LETTERS["L004"],LETTERS["L005"],LETTERS["L006"]]
results=[extract_fields(letter) for letter in letters]
df=pd.DataFrame(results)
display(df)

# TODO: Write BRIEF_PROMPT — it receives the letter AND your extracted JSON, and must output:
#     1. Strengths (bullet points, grounded in the letter)
#     2. Risks / red flags (bullet points)
#     3. Missing information the officer should request
#     4. Suggested next step (e.g. "invite for interview", "request documents",
#        "flag for senior review") — NOT "approve" or "reject".
#   Give the model an explicit instruction that final decisions are made by humans.
BRIEF_PROMPT="""
You are a model acting as an assistant to a microfinance loan officer. After the letter has been received,
use the extracted information to write a brief summary with:
1. Strengths (bullet points, grounded in the letter)
2. Risks / red flags (bullet points)
3. Missing information the officer should request
4. Suggested next step - Suggest a next step such as "invite for interview",
"request documents", "flag for senior review".
-Do not recomment approve or reject for the loan.
Final decisions should be made by human loan officers.
Loan application:{letter_text}
Extracted information:{extracted_json}"""
# TODO: Generate briefs for ALL SIX letters. Print the briefs for L001, L002, and L006 —
#   three very different applications.
briefs=[]
for i, letter in enumerate(letters):
  extracted_json=results[i]
  prompt=BRIEF_PROMPT.format(
      letter_text=letter,
      extracted_json=json.dumps(extracted_json)
  )
  response=ask_llm(prompt,temperature=0)
  briefs.append(response.choices[0].message.content
  )
print("L001")
print(briefs[0])
print("L002")
print(briefs[1])
print("L006")
print(briefs[5])

# TODO: For the three letters in GOLD, compare your extracted DataFrame to the gold values
#   field by field. Compute per-field accuracy across the three letters
#   (name matching can be case-insensitive; numbers must match exactly).
# TODO: Display a small table: rows = fields, columns = L001 / L003 / L006 / accuracy.

gold={"L001":{
    "applicant_name":"Akosua Mensah",
    "amount_ghs":8000,
    "purpose":"buy deep freezer / expand into frozen foods",
    "monthly_profit_ghs":900,
    "has_collateral_or_guarantor":True,
    "repayment_months":20,
},
      "L003":{
          "applicant_name":"Efua Darko",
          "amount_ghs":15000,
          "purpose":"industrial sewing machines and fabric stock",
          "monthly_profit_ghs":2800,
          "has_collateral_or_guarantor":True,
          "repayment_months":15,
      },
      "L006":{
          "applicant_name":"Kofi",
          "amount_ghs":50000,
          "purpose":"car wash, provision shop, phone imports",
          "monthly_profit_ghs":None,
          "has_collateral_or_guarantor":False,
          "repayment_months":12,

      }}
df["letter_id"]=["L001","L002","L003","L004","L005","L006"]
fields=["applicant_name","amount_ghs","purpose","monthly_profit_ghs","has_collateral_or_guarantor",
        "repayment_months"]
rows=[]
for field in fields:
  matches=[]
  for letter_id in ["L001","L003","L006"]:
    actual=df.loc[df["letter_id"]==letter_id, field].iloc[0]
    expected=gold[letter_id][field]
    if field=="applicant_name":
      match=str(actual).lower()==str(expected).lower()
    else:
      match=actual==expected
    matches.append(match)
  accuracy=sum(matches)/len(matches)
  rows.append({"field":field, "L001":matches[0], "L003": matches[1], "L006":matches[2], "accuracy":accuracy})
comparison=pd.DataFrame(rows)
display(comparison)

#TODO: Run extract_fields() on letter L004 FIVE times at temperature=0 and FIVE times at
#   temperature=1.0.
temperature_0_results=[]
temperature_1_results=[]
for i in range(5):
  temperature_0_results.append(extract_fields(LETTERS["L004"]))
for i in range(5):
  temperature_1_results.append(extract_fields(LETTERS["L004"], temperature=1.0))
#
# TODO: For each temperature, report how many of the 5 runs produced (a) valid JSON and
#   (b) identical values across runs. A simple approach: json.dumps(result, sort_keys=True)
#   and count unique strings.
firstvalid=sum([result is not None for result in temperature_0_results])
secondvalid=sum([result is not None for result in temperature_1_results])
firstunique=len(set(json.dumps(result, sort_keys=True)for result in temperature_0_results if result is not None))
secondunique=len(set(json.dumps(result, sort_keys=True)for result in temperature_1_results if result is not None))
print(f"Temperature 0: {firstvalid} valid, {firstunique} unique")
print(f"Temperature 1: {secondvalid} valid, {secondunique} unique")

from numpy import test

# TODO: Design TWO adversarial tests and run them:
#   Test 1 — Ask your summarizer a question about a detail that is NOT in a letter
#     (e.g. "What is the applicant's credit score?"). Does it admit the information is
#     absent, or does it invent one?
#   Test 2 — Feed your extractor an EMPTY or IRRELEVANT text (e.g. a weather report).
#     Does it return nulls, or does it fabricate an applicant?
firstprompt="""What is the applicant's credit score?"""
test1=ask_llm(f"{firstprompt}\n\nLetter:\n{LETTERS['L004']}",temperature=0)
print("TEST1 MISSING INFORMATION")
print(test1.choices[0].message.content)

secondprompt="""The weather is very suny this morning. It might rain in the afternoon, take along a raincoat and umbrella"""
test2=extract_fields(secondprompt, temperature=0)
print("TEST2 EMPTY/IRRELEVANT INFORMATION")
print(test2)
# TODO: Record the outputs verbatim below and label each PASS or FAIL.


#TEST 1-PASS
#TEST 2- FAIL

"""TASK 4.4
1. I'd say, people who do not have a high English speaking ability, or even limited formal education, could be unfairly harmed. This is because, their business may be very profitable, yet their poor English does not enable them express their situation effectively in the loan letter. The model may also mistake terrible writing for poor credit, which will basically lead to the exemption of small business owners who write poorly in english.

2. In sending a loan letter with personal data to to a third party API in another country,makes privacy, security and data protection be at risk.Before deploying this at a real Ghanaian microfinance institution, I will check how the API provider protects the data, where the data is stored, how long it is retained, and whether it can bbe delete and how it is processed.

3. Two concrete safeguards are:
a. Human review
The LLM will never approve or reject a loan automatically. This will be the duty of the human who is trained. The human is to check both the original application, and the output of the LLM before making a final decision.

b. Monitoring
The system should always be checking for errorsm and inaccuracies. Decisions made by both the LLM and the humans should be compared, to check if people are unfairly disadvantaged.

REFLECTION ANSWERS
1. Iterating on a prompt is similar to tuning model hyperparameters since both involve changing inputs to improve the performance of the model. In lab 3, hyperparameters such as the learnign rate and batch size were changed. But in this lab 4, i basically changed instructions in the prompt to improve the output of the LLM. The difference lies mainly in the fact that hyperparameters control how the model is trained whilst proompt engineering changes how a model thats already trained is instructed.

2. I will not trustt this system to run unattended. This is because the system may misinterpret loan applications, and makemistakes when extracting information. So it is necessary for humans loan officers to make the final decisions/ conclusion.

3. From my output  the total tokens were 56. So for 1000 applications, it will requrie 56000 tokens per month. It implies that i should choose a provider with affordable token pricing.

4. Calling an API beats training my own model because the foundation model is already trained which makes it faster and cheaper than training a model form scratch.
Training your own model would be better if the specialised data is in large amounts.

STUDENT REASONING ANSWERS
Section 1

Part 1.1
1. The System role tells the odel how to behave based on instructions it gives to it. example: "You are a helpful assistant"

The user role contains the actual task given to the model.example:"What is the capital of Ghana"

2. A token is a small piece of text the model processes, such as a word. API providers bill per token rather than per request because the longer the input and output, the more  resources used.



Part 1.2

When the temperature was 0.0, the answers were more consistent, whilst when the temperature was 1.2 the answers were different and more creative. For the loan decision support system i am  about to build, the temperature regime which i think is appropriate is temperature 0.0, since the system requires consistency and factuality and not merely creative responses.




Section 3

Part 3.1
1. V1 made assumptiond that were not supported. For example in L006, it said "he has no prior experience", yet the letter only said "has not started any of these yet". V2 corrected this by saying "Kofi has not yet initiated any of these ventures", which is closer to the letter.

2. It is called HALLUCINATION.


Part 3.2
1. This is because it can make the evaluation less indpenedent by influencing the models answers.

2. Without the instruction, the model may use assumptions to just fill places where information is missing.But using null ensures and makes it clear that the information was not provided.

3. Because, it makes extraction more consistent and predictable, which is a necessity for structured data. BUt, creative tasks can use higher temperatures because they gain more advantages from more varied responses.  


Part 3.3
1. Yes the system identified the right strengths and red flags in ecah. Because, for L003, it was strong since it had an established business, employees, sales recors, experience, monthly profit and collateral. But, L006 was the weak application since Kofi had no business experience, no collateral, hadnt started the business and wasnt certain about a repayment plan.

2. practical reason- The loan foficer must review the information before making a final decision since the LLM might make mistakes.

ethical reason- Loan decisions have a significant effect on the financial state of indivuals, so allowing AI to automatically aPPRove or reject it, may lead to bias and unfair decisions.






Section 4
1. Since there are 6 fields and 3 letters. The total comparisons ar 18. 14 were true. The overall accuracy was ((14/18))* 100 which gave me 77.77%.
The hardest field was purpose, which had 0% accuracy because the information the model gave was correct but the wording was different, and the evaluation required a precise match.

2. At both temperatures the 5/5 runs gave valid JSON and 1 unique result, and this showed that the extraction was very very consistent, signifying that the system is reliable for production.

3. The system did not clearly hallucinate. Test 1 passed because the model correctly said that the credit score was not provided.
Test 2 on the othe rhand returned {} instead of null, so it did not follow the extraction format. Then again, it did not create an applicant or give fake information.
To reduce the risk, the prompt should clearly instruct the model to return null for empty or irrelevant inputs, also, it should verify the JSON output before it accepts it.
"""